-- CREATE DATABASE transcend_db;

-- CREATE USER db_user WITH PASSWORD 'He11oWorld';

GRANT ALL PRIVILEGES ON DATABASE transcend_db TO db_user;

\c transcend_db

GRANT ALL PRIVILEGES ON SCHEMA public TO db_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO db_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO db_user;
