services:
  nginx:
    build:
      context: ./dockers/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockers/nginx/ssl:/etc/nginx/ssl
      - ./dockers/django/src/firstTry/staticfiles:/staticfiles
    depends_on:
      - django

  django:
    build:
      context: ./dockers/django
      dockerfile: Dockerfile
    container_name: django
    expose:
      - "8000"
    volumes:
      - ./dockers/django/src:/code
    depends_on:
      - db
    environment:
      - DB_NAME=transcend_db
      - DB_USER=db_user
      - DB_PASSWORD=He11oWorld
      - DB_HOST=db
      - DB_PORT=5432

  db:
    build:
      context: ./dockers/postgresql
      dockerfile: Dockerfile
    container_name: db
    environment:
      POSTGRES_DB: transcend_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: He11oWorld
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: