services:
  nginx:
    build:
      context: ./dockers/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "4243:443"
    volumes:
      # - ./localhost.conf:/etc/nginx/conf.d/default.conf
      - ./dockers/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - django

  django:
    build:
      context: ./dockers/django
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./dockers/django/src:/code
    depends_on:
      - db
    environment:
      - DB_NAME=transcend_db
      - DB_USER=db_user
      - DB_PASSWORD=He11oWorld
      - DB_HOST=db
      - DB_PORT=5432
    # command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  db:
    build:
      context: ./dockers/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: transcend_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: He11oWorld
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data
    ports:
      - "5432:5432"

volumes:
  pgdata: