services:
  nginx:
    build:
      context: ./dockers/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pong-network
    volumes:
      - ./dockers/nginx/ssl:/etc/nginx/ssl
      - ./dockers/django/src/transcendence/staticfiles:/staticfiles
    depends_on:
      - django

  django:
    build:
      context: ./dockers/django
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./dockers/django/src:/code
    depends_on:
      - db
    networks:
      - pong-network
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FORTY_TWO_CLIENT_ID: ${FORTY_TWO_CLIENT_ID}
      FORTY_TWO_CLIENT_SECRET: ${FORTY_TWO_CLIENT_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    build:
      context: ./dockers/postgresql
      dockerfile: Dockerfile
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - pong-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  pong-network:
    driver: bridge

volumes:
  pgdata:
